version: '3'
services:
    php:
        build: .
        networks:
            - backend
        expose:
            - "9000"
        volumes:
            - .:/var/www/html
    nginx:
        image: nginx:mainline-alpine
        networks:
          - backend
        ports:
          - '8080:8080'
        restart: on-failure
        volumes:
          - .:/var/www/html
          - ./nginx_config.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
        depends_on:
            - php
    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: umag_education
            MYSQL_USER: umag_education
            MYSQL_PASSWORD: secret
        networks:
            - backend
        ports:
            - '3306:3306'
        restart: on-failure
        volumes:
            - databaseVolume:/var/lib/mysql
    phpmyadmin:
        depends_on:
            - mariadb
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8092:80
        environment:
            PMA_HOST: mariadb
            PMA_USER: umag_education
            PMA_PASSWORD: secret
        networks:
            - backend    
volumes:
    databaseVolume: {}
networks:
    backend:
        driver: bridge

